POST http://localhost:4000/register
Content-Type: application/json

{
  "username": "adam_richard",
  "name": "Adam Richard",
  "password": "richard_567",
  "gender": "male",
  "location": "Detroit"
};

POST http://localhost:4000/ligin
Content-Type: application/json

{
  "username": "adam_richard",
  "password": "richard_567",
};

POST http://localhost:4000//change-password/
Content-Type: application/json
{
  "username": "adam_richard",
  "oldPassword": "richard_567",
  "newPassword": "richard@123"
}